version: "3.3"

services:
  webreactjs:
    image: khoanguyen1411/gpa-matching-frontend:release
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    restart: unless-stopped