export const UNIVERSITY_LIST = [
  "HỌC VIỆN Cán bộ TP.HCM",
  "HỌC VIỆN Công nghệ Bưu chính Viễn thông – Cơ sở TP.HCM",
  "HỌC VIỆN Hàng không Việt Nam",
  "Khoa Y - ĐH Quốc gia TP.HCM",
  "Nhạc viện TP.HCM",
  "Trường ĐẠI HỌC Bách Khoa - ĐHQG TP.HCM",
  "Trường ĐẠI HỌC Công nghệ Thông tin - ĐH Quốc gia TP.HCM",
  "Trường ĐẠI HỌC Công nghiệp Thực phẩm TP.HCM",
  "Trường ĐẠI HỌC Công nghiệp TP.HCM",
  "Trường ĐẠI HỌC Giao thông vận tải - Cơ sở 2",
  "Trường ĐẠI HỌC Giao thông vận tải TP.HCM",
  "Trường ĐẠI HỌC Hoa Sen",
  "Trường ĐẠI HỌC Khoa học Tự nhiên - ĐHQG TPHCM",
  "Trường ĐẠI HỌC Khoa học xã hội và Nhân văn - ĐHQG TP.HCM",
  "Trường ĐẠI HỌC Kiến trúc TP.HCM",
  "Trường ĐẠI HỌC Kinh tế - Tài chính TP.HCM",
  "Trường ĐẠI HỌC Kinh tế TP.HCM",
  "Trường ĐẠI HỌC Lao động Xã hội – Cơ sở TP.HCM",
  "Trường ĐẠI HỌC Luật TP.HCM",
  "Trường ĐẠI HỌC Mở TP.HCM",
  "Trường ĐẠI HỌC Mỹ thuật TP.HCM",
  "Trường ĐẠI HỌC Ngân hàng TP.HCM",
  "Trường ĐẠI HỌC Ngoại thương – Cơ sở phía Nam",
  "Trường ĐẠI HỌC Nguyễn Tất Thành",
  "Trường ĐẠI HỌC Nội vụ Hà Nội – Cơ sở tại TP.HCM",
  "Trường ĐẠI HỌC Nông Lâm TP.HCM",
  "Trường ĐẠI HỌC Quốc tế - ĐH Quốc gia TP.HCM",
  "Trường ĐẠI HỌC Quốc tếHồng Bàng",
  "Trường ĐẠI HỌC Sài Gòn",
  "Trường ĐẠI HỌC Sân khấu Điện ảnh TP.HCM",
  "Trường ĐẠI HỌC Sư phạm Kỹ thuật TP.HCM",
  "Trường ĐẠI HỌC Sư phạm TP.HCM",
  "Trường ĐẠI HỌC Tài chính -Marketing",
  "Trường ĐẠI HỌC Tài nguyên và Môi trường TP.HCM",
  "Trường ĐẠI HỌC Thể dục Thể thao TP.HCM",
  "Trường ĐẠI HỌC Thủy lợi – Cơ sở 2",
  "Trường ĐẠI HỌC Tôn Đức Thắng",
  "Trường ĐẠI HỌC Văn hóa TP.HCM",
  "Trường ĐẠI HỌC Việt - Đức",
  "Trường ĐẠI HỌC Y Dược TP.HCM",
  "Trường ĐẠI HỌC Y khoa Phạm Ngọc Thạch",
  "Trường ĐẠI HỌC Công nghệ Sài Gòn",
  "Trường ĐẠI HỌC Công nghệ thông tin Gia Định",
  "Trường ĐẠI HỌC Công nghệ TP.HCM",
  "Trường ĐẠI HỌC Hùng Vương",
  "Trường ĐẠI HỌC Kinh tế - Luật (ĐH Quốc gia TP.HCM)",
  "Trường ĐẠI HỌC Quốc tế Sài Gòn",
  "Trường ĐẠI HỌC Văn Hiến",
  "Trường ĐẠI HỌC Văn Lang",
  "Trường ĐẠI HỌC Sư phạm TDTT TP. HCM",
  "Trường ĐHNgoại ngữ - Tin học TP.HCM",

  "HỌC VIỆN Âm nhạc Quốc gia Việt Nam",
  "HỌC VIỆN Báo chí Tuyên truyền",
  "HỌC VIỆN Chính sách và Phát triển",
  "HỌC VIỆN Công nghệ Bưu chính Viễn thông",
  "HỌC VIỆN Hành chính Quốc gia",
  "HỌC VIỆN Kỹ thuật Mật mã",
  "HỌC VIỆN Ngân hàng",
  "HỌC VIỆN Ngoại giao",
  "HỌC VIỆN Nông nghiệp Việt Nam",
  "HỌC VIỆN Phụ nữ Việt Nam",
  "HỌC VIỆN Quản lý Giáo dục",
  "HỌC VIỆN Tài chính",
  "HỌC VIỆN Thanh Thiếu niên Việt Nam",
  "HỌC VIỆN Tòa án",
  "HỌC VIỆN Y Dược học cổ truyền Việt Nam",
  "Khoa Luật (ĐHQG Hà Nội)",
  "Khoa Quốc tế (ĐHQG Hà Nội)",
  "Khoa Y Dược (ĐHQG Hà Nội)",
  "Trường ĐẠI HỌC Bách khoa Hà Nội",
  "Trường ĐẠI HỌC Công đoàn",
  "Trường ĐẠI HỌC Công nghệ (ĐHQG Hà Nội)",
  "Trường ĐẠI HỌC Công nghệ Giao thông vận tải",
  "Trường ĐẠI HỌC Công nghiệp Dệt may Hà Nội",
  "Trường ĐẠI HỌC Công nghiệp Hà Nội",
  "Trường ĐẠI HỌC Công nghiệp Việt Hung",
  "Trường ĐẠI HỌC Đại Nam",
  "Trường ĐẠI HỌC Điện lực",
  "Trường ĐẠI HỌC Dược Hà Nội",
  "Trường ĐẠI HỌC FPT",
  "Trường ĐẠI HỌC Giao thông vận tải",
  "Trường ĐẠI HỌC Hà Nội",
  "Trường ĐẠI HỌC Hòa Bình",
  "Trường ĐẠI HỌC Khoa học và Công nghệ Hà Nội",
  "Trường ĐẠI HỌC Kiểm sát Hà Nội",
  "Trường ĐẠI HỌC Kiến trúc Hà Nội",
  "Trường ĐẠI HỌC Kinh tế (ĐHQG Hà Nội)",
  "Trường ĐẠI HỌC Kinh tế Kỹ thuật Công nghiệp",
  "Trường ĐẠI HỌC Kinh tế Quốc dân",
  "Trường ĐẠI HỌC Lâm nghiệp",
  "Trường ĐẠI HỌC Lao động Xã hội",
  "Trường ĐẠI HỌC Luật Hà Nội",
  "Trường ĐẠI HỌC Mỏ Địa chất Hà Nội",
  "Trường ĐẠI HỌC Mỹ thuật Công nghiệp",
  "Trường ĐẠI HỌC Mỹ thuật Công nghiệp Á Châu",
  "Trường ĐẠI HỌC Mỹ thuật Việt Nam",
  "Trường ĐẠI HỌC Ngoại ngữ (ĐHQG Hà Nội)",
  "Trường ĐẠI HỌC Ngoại thương",
  "Trường ĐẠI HỌC Nguyễn Trãi",
  "Trường ĐẠI HỌC Nội vụ Hà Nội",
  "Trường ĐẠI HỌC Quốc tế Bắc Hà",
  "Trường ĐẠI HỌC Sân khấu Điện ảnh",
  "Trường ĐẠI HỌC Sư phạm Hà Nội",
  "Trường ĐẠI HỌC Sư phạm Nghệ thuật Trung ương Hà Nội",
  "Trường ĐẠI HỌC Sư phạm Thể dục thể thao Hà nội",
  "Trường ĐẠI HỌC Tài chính Ngân hàng Hà Nội",
  "Trường ĐẠI HỌC Tài nguyên và Môi trường Hà Nội",
  "Trường ĐẠI HỌC Thăng Long",
  "Trường ĐẠI HỌC Thành Đô",
  "Trường ĐẠI HỌC Thành Tây",
  "Trường ĐẠI HỌC Thủ đô Hà Nội",
  "Trường ĐẠI HỌC Thương mại",
  "Trường ĐẠI HỌC Thủy lợi",
  "Trường ĐẠI HỌC Văn hóa Hà Nội",
  "Trường ĐẠI HỌC Xây dựng",
  "Trường ĐẠI HỌC Y Hà Nội",
  "Trường ĐẠI HỌC Y tế Công cộng",
  "Trường ĐẠI HỌC Công nghệ và Quản lý Hữu nghị",
  "Trường ĐẠI HỌC Đông Đô",
  "Trường ĐẠI HỌC Kinh doanh và Công nghệ Hà Nội",
  "Trường ĐẠI HỌC Phương Đông",
  "Trường ĐH Giáo dục(ĐHQG Hà Nội)",
  "Trường ĐH Khoa học Tự nhiên (ĐHQG Hà Nội)",
  "Trường ĐH Khoa học Xã hội và Nhân văn (ĐHQG Hà Nội)",
  "Viện ĐẠI HỌC Mở Hà Nội",

  "Trường ĐẠI HỌC An Giang",
  "Trường ĐẠI HỌC Bà Rịa - Vũng Tàu",
  "Trường ĐẠI HỌC Bạc Liêu",
  "Trường ĐẠI HỌC Bình Dương",
  "Trường ĐẠI HỌC Cần Thơ",
  "Trường ĐẠI HỌC Công nghệ Đồng Nai",
  "Trường ĐẠI HỌC Công nghệ Miền Đông",
  "Trường ĐẠI HỌC Dân lập Cửu Long",
  "Trường ĐẠI HỌC Dân lập Lạc Hồng",
  "Trường ĐẠI HỌC Dầu khí Việt Nam",
  "Trường ĐẠI HỌC Đồng Nai",
  "Trường ĐẠI HỌC Đồng Tháp",
  "Trường ĐẠI HỌC Kiên Giang",
  "Trường ĐẠI HỌC Kinh tế Công nghiệp Long An",
  "Trường ĐẠI HỌC Kinh tế Kỹ thuật Bình Dương",
  "Trường ĐẠI HỌC Kỹ thuật Công nghệ Cần Thơ",
  "Trường ĐẠI HỌC Lâm nghiệp – Cơ sở 2",
  "Trường ĐẠI HỌC Nam Cần Thơ",
  "Trường ĐẠI HỌC Quốc tế Miền Đông",
  "Trường ĐẠI HỌC Sư phạm Kỹ thuật Vĩnh Long",
  "Trường ĐẠI HỌC Tân Tạo",
  "Trường ĐẠI HỌC Tây Đô",
  "Trường ĐẠI HỌC Thủ Dầu Một",
  "Trường ĐẠI HỌC Tiền Giang",
  "Trường ĐẠI HỌC Trà Vinh",
  "Trường ĐẠI HỌC Việt – Đức",
  "Trường ĐẠI HỌC Võ Trường Toản",
  "Trường ĐẠI HỌC Xây dựng Miền Tây",
  "Trường ĐẠI HỌC Y Dược Cần Thơ",

  "ĐẠI HỌC Thái Nguyên",
  "Khoa Ngoại ngữ (ĐH Thái Nguyên)",
  "Khoa Quốc tế (ĐH Thái Nguyên)",
  "Phân hiệu ĐẠI HỌC Thái Nguyên tại Lào Cai",
  "Trường ĐẠI HỌC Chu Văn An",
  "Trường ĐẠI HỌC Công nghệ Đông Á",
  "Trường ĐẠI HỌC Công nghệ TT và Truyền thông (ĐH Thái Nguyên)",
  "Trường ĐẠI HỌC Công nghiệp Quảng Ninh",
  "Trường ĐẠI HỌC Công nghiệp Việt Trì",
  "Trường ĐẠI HỌC Dân lập Hải Phòng",
  "Trường ĐẠI HỌC Dân lập Lương Thế Vinh",
  "Trường ĐẠI HỌC Điều dưỡng Nam Định",
  "Trường ĐẠI HỌC Hạ Long",
  "Trường ĐẠI HỌC Hải Dương",
  "Trường ĐẠI HỌC Hải Phòng",
  "Trường ĐẠI HỌC Hàng hải",
  "Trường ĐẠI HỌC Hoa Lư",
  "Trường ĐẠI HỌC Hồng Đức",
  "Trường ĐẠI HỌC Hùng Vương",
  "Trường ĐẠI HỌC Khoa học (ĐH Thái Nguyên)",
  "Trường ĐẠI HỌC Kinh Bắc",
  "Trường ĐẠI HỌC Kinh tế - Quản trị kinh doanh (ĐH Thái Nguyên)",
  "Trường ĐẠI HỌC Kỹ thuật Công nghiệp (ĐH Thái Nguyên)",
  "Trường ĐẠI HỌC Kỹ thuật Y tế Hải Dương",
  "Trường ĐẠI HỌC Nông lâm (ĐH Thái Nguyên)",
  "Trường ĐẠI HỌC Nông Lâm Bắc Giang",
  "Trường ĐẠI HỌC Quốc tế Bắc Hà",
  "Trường ĐẠI HỌC Sao Đỏ",
  "Trường ĐẠI HỌC Sư phạm (ĐH Thái Nguyên)",
  "Trường ĐẠI HỌC Sư phạm Hà Nội 2",
  "Trường ĐẠI HỌC Sư phạm Kỹ thuật Hưng Yên",
  "Trường ĐẠI HỌC Sư phạm Kỹ thuật Nam Định",
  "Trường ĐẠI HỌC Tài chính - Quản trị kinh doanh",
  "Trường ĐẠI HỌC Tân Trào",
  "Trường ĐẠI HỌC Tây Bắc",
  "Trường ĐẠI HỌC Thái Bình",
  "Trường ĐẠI HỌC Thành Đông",
  "Trường ĐẠI HỌC Thể dục Thể thao Bắc Ninh",
  "Trường ĐẠI HỌC Trưng Vương",
  "Trường ĐẠI HỌC Văn hóa Thể thao và Du lịch Thanh Hóa",
  "Trường ĐẠI HỌC Việt Bắc",
  "Trường ĐẠI HỌC Y Dược (ĐH Thái Nguyên)",
  "Trường ĐẠI HỌC Y Dược Hải Phòng",
  "Trường ĐẠI HỌC Y Dược Thái Bình",
  "Trường ĐẠI HỌC Y khoa Tokyo Việt Nam",

  "HỌC VIỆN Âm nhạc Huế",
  "Khoa Công nghệ - ĐH Đà Nẵng",
  "Khoa Công nghệ thông tin và Truyền thông – ĐH Đà Nẵng",
  "Khoa Du lịch - ĐH Huế",
  "Khoa Giáo dục Thể chất – ĐH Đà Nẵng",
  "Khoa Giáo dục Thể chất - ĐH Huế",
  "Khoa Y Dược – ĐH Đà Nẵng",
  "Phân hiệu ĐẠI HỌC Đà Nẵng tại Kon Tum",
  "Phân hiệu ĐH Huế tại quảng Trị",
  "Trường ĐẠI HỌC Bách Khoa - ĐH Đà Nẵng",
  "Trường ĐẠI HỌC Buôn Ma Thuột",
  "Trường ĐẠI HỌC Công nghệ Vạn Xuân",
  "Trường ĐẠI HỌC Công nghiệp Vinh",
  "Trường ĐẠI HỌC Đà Lạt",
  "Trường ĐẠI HỌC Dân lập Duy Tân",
  "Trường ĐẠI HỌC Dân lập Phú Xuân",
  "Trường ĐẠI HỌC Dân lập Yersin Đà Lạt",
  "Trường ĐẠI HỌC Đông Á",
  "Trường ĐẠI HỌC Hà Tĩnh",
  "Trường ĐẠI HỌC Khánh Hòa",
  "Trường ĐẠI HỌC Khoa học - ĐH Huế",
  "Trường ĐẠI HỌC Kiến trúc Đà Nẵng",
  "Trường ĐẠI HỌC Kinh tế - ĐH Đà Nẵng",
  "Trường ĐẠI HỌC Kinh tế - ĐH Huế",
  "Trường ĐẠI HỌC Kinh tế Nghệ An",
  "Trường ĐẠI HỌC Kỹ thuật Y Dược Đà Nẵng",
  "Trường ĐẠI HỌC Luật - ĐH Huế",
  "Trường ĐẠI HỌC Nghệ thuật - ĐH Huế",
  "Trường ĐẠI HỌC Ngoại ngữ - ĐH Đà Nẵng",
  "Trường ĐẠI HỌC Ngoại ngữ - ĐH Huế",
  "Trường ĐẠI HỌC Nha Trang",
  "Trường ĐẠI HỌC Nông Lâm - ĐH Huế",
  "Trường ĐẠI HỌC Phạm Văn Đồng",
  "Trường ĐẠI HỌC Phan Châu Trinh",
  "Trường ĐẠI HỌC Phan Thiết",
  "Trường ĐẠI HỌC Phú Yên",
  "Trường ĐẠI HỌC Quảng Bình",
  "Trường ĐẠI HỌC Quảng Nam",
  "Trường ĐẠI HỌC Quang Trung",
  "Trường ĐẠI HỌC Quy Nhơn",
  "Trường ĐẠI HỌC Sư phạm - ĐH Đà nẵng",
  "Trường ĐẠI HỌC Sư phạm - ĐH Huế",
  "Trường ĐẠI HỌC Sư phạm Kỹ thuật – ĐH Đà Nẵng",
  "Trường ĐẠI HỌC Sư phạm Kỹ thuật Vinh",
  "Trường ĐẠI HỌC Tài chính Kế toán",
  "Trường ĐẠI HỌC Tây Nguyên",
  "Trường ĐẠI HỌC Thái Bình Dương",
  "Trường ĐẠI HỌC Thể dục Thể thao Đà Nẵng",
  "Trường ĐẠI HỌC Vinh",
  "Trường ĐẠI HỌC Xây dựng Miền Trung",
  "Trường ĐẠI HỌC Y Dược - ĐH Huế",
  "Trường ĐẠI HỌC Y khoa Vinh",
  "HỌC VIỆN Biên phòng",
  "HỌC VIỆN Hải Quân",
  "HỌC VIỆN Hậu cần",
  "HỌC VIỆN Khoa học Quân sự",
  "HỌC VIỆN Kỹ thuật Quân sự",
  "HỌC VIỆN Phòng không - Không quân",
  "HỌC VIỆN Quân Y",
  "Trường ĐẠI HỌC Chính trị (Trường SĨ QUAN Chính trị)",
  "Trường ĐẠI HỌC Văn hóa - Nghệ thuật Quân đội",
  "Trường SĨ QUAN Công binh",
  "Trường SĨ QUAN Đặc công",
  "Trường SĨ QUAN không quân",
  "Trường SĨ QUAN Kỹ thuật QS Vinhempich (ĐH Trần Đại Nghĩa)",
  "Trường SĨ QUAN Lục quân 1 (ĐH Trần Quốc Tuấn)",
  "Trường SĨ QUAN Lục quân 2 (ĐH Nguyễn Huệ)",
  "Trường SĨ QUAN Pháo binh",
  "Trường SĨ QUAN Phòng Hóa",
  "Trường SĨ QUAN Tăng - Thiết giáp",
  "Trường SĨ QUAN Thông tin",

  "HỌC VIỆN An ninh Nhân dân",
  "HỌC VIỆN Cảnh sát Nhân dân",
  "HỌC VIỆN Chính trị Công an Nhân dân",
  "Trường ĐẠI HỌC An ninh nhân dân",
  "Trường ĐẠI HỌC Cảnh sát nhân dân",
  "Trường ĐẠI HỌC Kỹ thuật - Hậu cần Công an nhân dân",
  "Trường ĐẠI HỌC Phòng cháy chữa cháy",
];
