name: Check build

on:
  push:
    branches: ["develop", "staging", "master"]
  pull_request:
    branches: ["develop", "staging", "master"]

jobs: 
  check-build: 
    runs-on: ubuntu-latest
    steps: 
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: yarn
    - name: Build application
      run: yarn build
       