name: Lint ci/cd

on:
  push:
    branches: ["develop", "staging", "master"]
  pull_request:
    branches: ["develop", "staging", "master"]

jobs: 
  check-eslint-stage: 
    runs-on: ubuntu-latest
    steps: 
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: yarn
    - name: Check eslint and prettier
      run: yarn fix-all
       